---
title: "2.export_for_RPCA_and_QIIME"
author: "Deepan"
date: "12/18/2024"
output: html_document
---

## Load libraries

```{r, message = FALSE}
# Packages I commonly use
# install.packages("stringr")
# install.packages("ggplot2")
# install.packages("reshape")
# install.packages("reshape2")
# install.packages("gplots")
# install.packages("FactoMineR")
# install.packages("factoextra")
library(stringr)
library(ggplot2)
library(FactoMineR)
library(factoextra)
library(reshape)
library(reshape2)
library(gplots)
library(RColorBrewer)
```

## Import formatted df

```{r}

df <- read.delim2("/media/deepan/Deepan/LiveDead/igm-storage2.ucsd.edu/220428_A00953_0539_AHMNLKDSX3/202410_revision/swab_blank_removed/skin_SMGC_Zebra60perc_formatted.tsv", check.names = FALSE)

df[, -1] <- sapply(df[, -1], as.numeric)

```

## Export tables for RPCA: all, PMA treated , Raw

```{r}

write.table( df[, colnames(df) %in% c( "#OTU ID", colnames(df)[str_detect(colnames(df), "-PMA")])], "/media/deepan/Deepan/LiveDead/igm-storage2.ucsd.edu/220428_A00953_0539_AHMNLKDSX3/202410_revision/swab_blank_removed/Final_rpca_pma.tsv", row.names = FALSE, sep = "\t" )

write.table( df[, colnames(df) %in% c( "#OTU ID", colnames(df)[!str_detect(colnames(df), "-PMA")])], "/media/deepan/Deepan/LiveDead/igm-storage2.ucsd.edu/220428_A00953_0539_AHMNLKDSX3/202410_revision/swab_blank_removed/Final_rpca_raw.tsv", row.names = FALSE, sep = "\t" )

write.table( df, "/media/deepan/Deepan/LiveDead/igm-storage2.ucsd.edu/220428_A00953_0539_AHMNLKDSX3/202410_revision/swab_blank_removed/Final_rpca_all.tsv", row.names = FALSE, sep = "\t" )

```

