---
title: "5. PMA_Index"
author: "Deepan"
date: "12/28/2024"
output: html_document
---

## Load libraries

```{r, message = FALSE}
# Packages I commonly use
# install.packages("stringr")
# install.packages("ggplot2")
# install.packages("reshape")
# install.packages("reshape2")
# install.packages("gplots")
# install.packages("FactoMineR")
# install.packages("factoextra")
library(stringr)
library(ggplot2)
library(FactoMineR)
library(factoextra)
library(reshape)
library(reshape2)
library(gplots)
library(RColorBrewer)
```

## Import RPKM normalized sorted dataframe

```{r}

df <- read.delim2("/media/deepan/Deepan/LiveDead/igm-storage2.ucsd.edu/220428_A00953_0539_AHMNLKDSX3/202410_revision/swab_blank_removed/skin_SMGC_Zebra60perc_formatted_RPKM_sorted.tsv", check.names = FALSE) #only samples with paired Raw and PMA-treated

df[, -1] <- sapply(df[, -1], as.numeric)

order <- unique(df$Taxa)

```

## Aggregate by taxa

```{r}

df <- aggregate(df[, -1], by = list( df$Taxa), sum)

df$Group.1 <- ordered(df$Group.1, levels = order)

df <- df[order(df$Group.1), ]

```


## Split PMA and Raw

```{r}

index <- melt(df[ df$Group.1 != "other" , colnames(df) %in% c("Group.1", colnames(df)[str_detect(colnames(df), "PMA")])]) #only grabbing PMA samples first

index$bs <- str_split(index$variable, "-", simplify = TRUE)[, 2]

index$unique <- paste(index$Group.1, index$variable, sep = "-")

index <- index[, c(5, 3)]

colnames(index)[2] <- "RA_PMA"

index$unique <- str_replace(index$unique, "-PMA", "")

temp <- melt(df[ df$Group.1 != "other" , colnames(df) %in% c("Group.1", colnames(df)[!str_detect(colnames(df), "PMA")])]) #only grabbing PMA samples first

temp$bs <- str_split(temp$variable, "-", simplify = TRUE)[, 2]

temp$unique <- paste(temp$Group.1, temp$variable, sep = "-")

temp <- temp[, c(5, 3)]

colnames(temp)[2] <- "RA_Raw"

index <- merge(index, temp, by = "unique")

index$Index <- index$RA_PMA / (index$RA_PMA + index$RA_Raw)

index <- index[, c(1, 4)]

```

## Aggregating by average and computing sd

```{r}

index$unique <- paste( str_split(index$unique, "-", simplify = TRUE)[, 1], str_split(index$unique, "-", simplify = TRUE)[, 3], sep = "-")

plot <- aggregate(index[ , 2], by = list(index$unique), mean)

colnames(plot)[2] <- "Index" 

plot <- merge( plot, aggregate(index[ , 2], by = list(index$unique), sd))

colnames(plot)[3] <- "SD"

```


## Plotting

```{r}

plot$Taxa <- str_split(plot$Group.1, "-", simplify = TRUE)[, 1]
plot$BS <- str_split(plot$Group, "-", simplify = TRUE)[, 2]

plot$SkinType <- ifelse( plot$BS %in% c( "FH", "UB"), "Sebaceous",
                        ifelse( plot$BS %in% c( "AC", "PC"), "Moist", "Dry"))

plot <- plot[, c(4, 2, 3, 5, 6)]

ggplot(plot, aes(x = BS, y = ordered(Taxa, levels = order[order != "other"]), fill = Index)) +
  geom_tile(color = "black", width = 1, height = 1, size = 0.25) +
  geom_text(aes(label = round(SD, 2), color = SD), size = 3) +
  scale_fill_gradient2(low = "#007c7c", mid = "#ffffff", high = "#ffd700", midpoint = 0.5, name = "Index") +
  scale_color_gradient(low = "lightgrey", high = "red", name = "SD") +
  labs(x = "Body Site", y = "Taxa", fill = "Index") +
  theme_minimal() +
  scale_y_discrete(limits = rev(levels(ordered(plot$Taxa, levels = order[order != "other"])))) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    panel.grid = element_blank(),
    legend.position = "right"
  )

```


